[package]
name = "rust-nes"
version = "0.1.0"
edition = "2021"

[profile.dev]
lto = true
opt-level = 2
debug = 2
codegen-units = 1

[profile.release]
opt-level = 3
lto = true
debug = false

[build-dependencies]
cc = { version = "1.0"}
