[package]
name = "meta_nestris"
version = "0.2.0"
edition = "2021"

[dependencies]
bitmask-enum = "=2.1.0"
# once_cell = "=1.16.0"

# [dependencies.bitvec]
# version = "1"
# default-features = false
# features = []
