[build]
target = "mos-nes-cnrom-none"

[target.mos-nes-cnrom-none]
rustflags = [
  # "-C",
  # "link-arg=-Tlink.ld",
  # "-C",
  # "link-arg=-Wl,-Map=output.map"
]


[unstable]
build-std = ["core", "alloc"]
